IF DB_ID('{DB_NAME}') IS NULL
BEGIN
	CREATE DATABASE [{DB_NAME}]
END

GO

USE [{DB_NAME}]

IF OBJECT_ID('dbo.Customer') IS NULL
BEGIN
	CREATE TABLE [Customer]
	(
		[Id] INT IDENTITY PRIMARY KEY,
		[Name] VARCHAR(50) NOT NULL,
		[Address] VARCHAR(300) NOT NULL,
		[Email] VARCHAR(100) NOT NULL,
		[Phone] VARCHAR(20) NOT NULL
	)
END

CREATE UNIQUE NONCLUSTERED INDEX UX_Name ON dbo.Customer([Name])
CREATE UNIQUE NONCLUSTERED INDEX UX_Email ON dbo.Customer([Email])
CREATE UNIQUE NONCLUSTERED INDEX UX_Phone ON dbo.Customer([Phone])